version: '>= 0.14.0'

formatter: markdown table

content: |-
  # Terraform ACI Fabric Leaf Interface Selector Module

  Manages ACI Fabric Leaf Interface Selector

  Location in GUI:
  `Fabric` » `Fabric Policies` » `Interfaces` » `Leaf Interfaces` » `Profiles` » `XXX`

  ## Examples

  ```hcl
  {{ include "./examples/complete/main.tf" }}
  ```

  {{ .Requirements }}

  {{ .Providers }}

  {{ .Inputs }}

  {{ .Outputs }}

  {{ .Resources }}

output:
  file: README.md
  mode: replace

sort:
  enabled: false
