version: '>= 0.14.0'

formatter: markdown table

content: |-
  # Terraform ACI OOB Contract Module

  Manages ACI OOB Contract

  Location in GUI:
  `Tenants` » `mgmt` » `Contracts` » `Out-Of-Band Contracts`

  ## Examples

  ```hcl
  {{ include "./examples/complete/main.tf" }}
  ```

  {{ .Requirements }}

  {{ .Providers }}

  {{ .Inputs }}

  {{ .Outputs }}

  {{ .Resources }}

output:
  file: README.md
  mode: replace

sort:
  enabled: false
