version: '>= 0.14.0'

formatter: markdown table

content: |-
  # Terraform ACI RBAC Node Rule Module

  Manages ACI RBAC Node Rule

  Location in GUI:
  `Admin` » `AAA` » `Security` » `RBAC Rules` » `Node Rules`

  ## Examples

  ```hcl
  {{ include "./examples/complete/main.tf" }}
  ```

  {{ .Requirements }}

  {{ .Providers }}

  {{ .Inputs }}

  {{ .Outputs }}

  {{ .Resources }}

output:
  file: README.md
  mode: replace

sort:
  enabled: false
