version: '>= 0.14.0'

formatter: markdown table

content: |-
  [![Tests](https://github.com/netascode/terraform-aci-service-graph-template/actions/workflows/test.yml/badge.svg)](https://github.com/netascode/terraform-aci-service-graph-template/actions/workflows/test.yml)

  # Terraform ACI Service Graph Template Module

  Manages ACI Service Graph Template

  Location in GUI:
  `Tenants` » `XXX` » `Services` » `L4-L7` » `Service Graph Templates`

  ## Examples

  ```hcl
  {{ include "./examples/complete/main.tf" }}
  ```

  {{ .Requirements }}

  {{ .Providers }}

  {{ .Inputs }}

  {{ .Outputs }}

  {{ .Resources }}

output:
  file: README.md
  mode: replace

sort:
  enabled: false
