version: '>= 0.14.0'

formatter: markdown table

content: |-
  # Terraform ACI Smart Licensing Module

  Manages ACI Smart Licensing

  Location in GUI:
  `System` » `Smart Licensing`

  ## Examples

  ```hcl
  {{ include "./examples/complete/main.tf" }}
  ```

  {{ .Requirements }}

  {{ .Providers }}

  {{ .Inputs }}

  {{ .Outputs }}

  {{ .Resources }}

output:
  file: README.md
  mode: replace

sort:
  enabled: false
