version: '>= 0.14.0'

formatter: markdown table

content: |-
  [![Tests](https://github.com/netascode/terraform-aci-endpoint-loop-protection/actions/workflows/test.yml/badge.svg)](https://github.com/netascode/terraform-aci-endpoint-loop-protection/actions/workflows/test.yml)

  # Terraform ACI Endpoint Loop Protection Module

  Manages ACI Endpoint Loop Protection

  Location in GUI:
  `System` » `System Settings` » `Endpoint Controls`

  ## Examples

  ```hcl
  {{ include "./examples/complete/main.tf" }}
  ```

  {{ .Requirements }}

  {{ .Providers }}

  {{ .Inputs }}

  {{ .Outputs }}

  {{ .Resources }}

output:
  file: README.md
  mode: replace

sort:
  enabled: false
