version: ">= 0.14.0"

formatter: markdown table

content: |-
  [![Tests](https://github.com/netascode/terraform-aci-interface-configuration/actions/workflows/test.yml/badge.svg)](https://github.com/netascode/terraform-aci-interface-configuration/actions/workflows/test.yml)

  # Terraform ACI Interface Configuration Module

  Manages ACI Interface Configuration

  Location in GUI:
  `Fabric` » `Access Policies` » `Interface Configuration`

  ## Examples

  ```hcl
  {{ include "./examples/complete/main.tf" }}
  ```

  {{ .Requirements }}

  {{ .Providers }}

  {{ .Inputs }}

  {{ .Outputs }}

  {{ .Resources }}

output:
  file: README.md
  mode: replace

sort:
  enabled: false
