version: '>= 0.14.0'

formatter: markdown table

content: |-
  [![Tests](https://github.com/netascode/terraform-aci-fabric-pod-profile/actions/workflows/test.yml/badge.svg)](https://github.com/netascode/terraform-aci-fabric-pod-profile/actions/workflows/test.yml)

  # Terraform ACI Fabric Pod Profile Module

  Manages ACI Fabric Pod Profile

  Location in GUI:
  `Fabric` » `Fabric Policies` » `Pods` » `Profiles`

  ## Examples

  ```hcl
  {{ include "./examples/complete/main.tf" }}
  ```

  {{ .Requirements }}

  {{ .Providers }}

  {{ .Inputs }}

  {{ .Outputs }}

  {{ .Resources }}

output:
  file: README.md
  mode: replace

sort:
  enabled: false
