---
kind: pipeline
type: docker
name: Pipeline

concurrency:
  limit: 1

environment:
  PY_COLORS: "1"
  ANSIBLE_FORCE_COLOR: "1"

trigger:
  branch:
    - master

clone:
  disable: true

steps:
  - name: Clone Repo
    image: drone/git
    pull: if-not-exists

  - name: Test Validate
    image: danischm/aac:0.5.10
    commands:
      - pytest -m validate
    depends_on:
      - Clone Repo

  - name: Test APIC 4.2
    image: danischm/aac:0.5.10
    environment:
      VMWARE_HOST:
        from_secret: VMWARE_HOST
      VMWARE_USER:
        from_secret: VMWARE_USER
      VMWARE_PASSWORD:
        from_secret: VMWARE_PASSWORD
      ACI_USERNAME:
        from_secret: ACI_USERNAME
      ACI_PASSWORD:
        from_secret: ACI_PASSWORD
    commands:
      - pytest -m "apic_42 and not terraform"
    depends_on:
      - Clone Repo

  - name: Test APIC 5.2
    image: danischm/aac:0.5.10
    environment:
      VMWARE_HOST:
        from_secret: VMWARE_HOST
      VMWARE_USER:
        from_secret: VMWARE_USER
      VMWARE_PASSWORD:
        from_secret: VMWARE_PASSWORD
      ACI_USERNAME:
        from_secret: ACI_USERNAME
      ACI_PASSWORD:
        from_secret: ACI_PASSWORD
    commands:
      - pytest -m "apic_52 and not terraform"
    depends_on:
      - Clone Repo

  - name: Test NDO
    image: danischm/aac:0.5.10
    environment:
      VMWARE_HOST:
        from_secret: VMWARE_HOST
      VMWARE_USER:
        from_secret: VMWARE_USER
      VMWARE_PASSWORD:
        from_secret: VMWARE_PASSWORD
      MSO_USERNAME:
        from_secret: MSO_USERNAME
      MSO_PASSWORD:
        from_secret: MSO_PASSWORD
    commands:
      - pytest -m ndo
    depends_on:
      - Clone Repo

  - name: Upload Reports
    image: jmccann/drone-artifactory:3.3
    settings:
      username: as-deployer
      password:
        from_secret: ARTIFACTORY_PASSWORD
      url: https://engci-maven.cisco.com/artifactory
      actions:
        - action: upload
          path: AS-release/Community/${DRONE_REPO_OWNER}/${DRONE_REPO_NAME}/${DRONE_BUILD_NUMBER}/
          sources:
            - apic_4.2_log.html
            - apic_5.2_log.html
            - ndo_log.html
    when:
      status: [changed, failure, success]
    depends_on:
      - Test Validate
      - Test APIC 4.2
      - Test APIC 5.2
      - Test NDO

  - name: Build Documentation
    image: danischm/aac:0.5.10
    commands:
      - pip install --upgrade mkdocs mkdocs-material mkdocs-mermaid2-plugin
      - python3 docs/aac-doc.py
      - mkdocs build
    when:
      branch:
        - master
      event:
        - push
    depends_on:
      - Clone Repo

  - name: Deploy Documentation
    image: appleboy/drone-scp:1.6.3
    settings:
      host: aac.cisco.com
      username:
        from_secret: HOST_USERNAME
      password:
        from_secret: HOST_PASSWORD
      target: /www/aac/
      source: site/
    when:
      branch:
        - master
      event:
        - push
    depends_on:
      - Build Documentation

  - name: Notify
    image: danischm/aac:0.5.10
    environment:
      WEBEX_TOKEN:
        from_secret: SPARK_ACCESS_TOKEN
      WEBEX_ROOM_ID: "Y2lzY29zcGFyazovL3VzL1JPT00vNTFmMGNmODAtYjI0My0xMWU5LTljZjUtNWY0NGQ2ZTlmYWY0"
    commands:
      - python3 .ci/webex-notification-drone.py
    when:
      status: [changed, failure, success]
    depends_on:
      - Upload Reports
      - Deploy Documentation
