---
kind: pipeline
type: docker
name: Pipeline

concurrency:
  limit: 1

environment:
  PY_COLORS: '1'
  ANSIBLE_FORCE_COLOR: '1'

trigger:
  branch:
    - master

clone:
  disable: true

steps:
  - name: Clone Repo
    image: drone/git
    pull: if-not-exists

  - name: Test Validate
    image: danischm/aac:0.3.5
    commands:
      - pytest -m validate
    depends_on:
      - Clone Repo

  - name: Test APIC
    image: danischm/aac:0.3.5
    environment:
      VMWARE_HOST:
        from_secret: VMWARE_HOST
      VMWARE_USER:
        from_secret: VMWARE_USER
      VMWARE_PASSWORD:
        from_secret: VMWARE_PASSWORD
      ACI_USERNAME:
        from_secret: ACI_USERNAME
      ACI_PASSWORD:
        from_secret: ACI_PASSWORD
    commands:
      - pytest -m apic
    depends_on:
      - Clone Repo

  - name: Test MSO
    image: danischm/aac:0.3.5
    environment:
      VMWARE_HOST:
        from_secret: VMWARE_HOST
      VMWARE_USER:
        from_secret: VMWARE_USER
      VMWARE_PASSWORD:
        from_secret: VMWARE_PASSWORD
      MSO_USERNAME:
        from_secret: MSO_USERNAME
      MSO_PASSWORD:
        from_secret: MSO_PASSWORD
    commands:
      - pytest -m mso
    depends_on:
      - Clone Repo

  - name: Upload Reports
    image: jmccann/drone-artifactory:3.3
    settings:
      username: as-deployer
      password:
        from_secret: ARTIFACTORY_PASSWORD
      url: https://engci-maven.cisco.com/artifactory
      actions:
        - action: upload
          path: AS-release/Community/netascode/aac/${DRONE_BUILD_NUMBER}/
          sources:
            - apic_4.2_log.html
            - apic_5.2_log.html
            - mso_log.html
    when:
      status: [changed, failure, success]
    depends_on:
      - Test Validate
      - Test APIC
      - Test MSO

  - name: Build Documentation
    image: danischm/aac:0.3.5
    commands:
      - pip install --upgrade mkdocs mkdocs-material mkdocs-mermaid2-plugin
      - python3 docs/aac-doc.py
      - mkdocs build
    when:
      branch:
        - master
      event:
        - push
    depends_on:
      - Clone Repo

  - name: Deploy Documentation
    image: appleboy/drone-scp:1.6.3
    settings:
      host: aac.cisco.com
      username:
        from_secret: HOST_USERNAME
      password:
        from_secret: HOST_PASSWORD
      target: /www/aac/
      source: site/
    when:
      branch:
        - master
      event:
        - push
    depends_on:
      - Build Documentation

  - name: Notify
    image: ciscosso/drone-webex-team:v0.0.1
    settings:
      pull: true
      room: 'AAC Builds'
      room_id: 'Y2lzY29zcGFyazovL3VzL1JPT00vNTFmMGNmODAtYjI0My0xMWU5LTljZjUtNWY0NGQ2ZTlmYWY0'
      access_token:
        from_secret: SPARK_ACCESS_TOKEN
      body: |
        [**[{{ build.status }}] {{ repo.owner }}/{{ repo.name }} #{{ build.number }}**]({{ build.link }})
        * Commit: [{{ commit.message }}]({{ commit.link }})
        * Author: {{ commit.author.name }} {{ commit.author.email }}
        * Branch: {{ commit.branch }}
        * Event: {{ build.event }}
        * Started at: {{ datetime build.created "Mon Jan 2 15:04:05 MST 2006" "Local" }}
        * Test Reports: [APIC 4.2](https://engci-maven-master.cisco.com/artifactory/list/AS-release/Community/netascode/aac/{{ build.number }}/apic_4.2_log.html) [APIC 5.2](https://engci-maven-master.cisco.com/artifactory/list/AS-release/Community/netascode/aac/{{ build.number }}/apic_5.2_log.html) [MSO](https://engci-maven-master.cisco.com/artifactory/list/AS-release/Community/netascode/aac/{{ build.number }}/mso_log.html)
    when:
      status: [changed, failure, success]
    depends_on:
      - Upload Reports
      - Deploy Documentation
