version: '>= 0.14.0'

formatter: markdown table

content: |-
  # Terraform ACI Bridge Domain Module

  Manages ACI Bridge Domain

  Location in GUI:
  `Tenants` » `XXX` » `Networking` » `Bridge Domains`

  ## Examples

  ```hcl
  {{ include "./examples/complete/main.tf" }}
  ```

  {{ .Requirements }}

  {{ .Providers }}

  {{ .Inputs }}

  {{ .Outputs }}

  {{ .Resources }}

output:
  file: README.md
  mode: replace

sort:
  enabled: false
