version: '>= 0.14.0'

formatter: markdown table

content: |-
  # Terraform ACI Tenant Netflow Monitor Module

  Manages ACI Netflow Monitors

  Location in GUI:
  `Tenant` » `XXX` » `Policies` » `NetFlow Monitors`

  ## Examples

  ```hcl
  {{ include "./examples/complete/main.tf" }}
  ```

  {{ .Requirements }}

  {{ .Providers }}

  {{ .Inputs }}

  {{ .Outputs }}

  {{ .Resources }}

output:
  file: README.md
  mode: replace

sort:
  enabled: false
