version: ">= 0.14.0"

formatter: markdown table

content: |-
  # Terraform ACI Switch Configuration Module

  Manages ACI Switch Configuration

  Location in GUI:
  `Fabric` » `Access Policies` » `Switch Configuration`

  ## Examples

  ```hcl
  {{ include "./examples/complete/main.tf" }}
  ```

  {{ .Requirements }}

  {{ .Providers }}

  {{ .Inputs }}

  {{ .Outputs }}

  {{ .Resources }}

output:
  file: README.md
  mode: replace

sort:
  enabled: false
