version: '>= 0.14.0'

formatter: markdown table

content: |-
  # Terraform ACI Redirect Health Group Module

  Manages ACI Redirect Health Group

  Location in GUI:
  `Tenants` » `XXX` » `Policies` » `Protocol` » `L4-L7 Redirect Health Groups`

  ## Examples

  ```hcl
  {{ include "./examples/complete/main.tf" }}
  ```

  {{ .Requirements }}

  {{ .Providers }}

  {{ .Inputs }}

  {{ .Outputs }}

  {{ .Resources }}

output:
  file: README.md
  mode: replace

sort:
  enabled: false
