version: '>= 0.14.0'

formatter: markdown table

content: |-
  [![Tests](https://github.com/netascode/terraform-aci-fabric-wide-settings/actions/workflows/test.yml/badge.svg)](https://github.com/netascode/terraform-aci-fabric-wide-settings/actions/workflows/test.yml)

  # Terraform ACI Fabric Wide Settings Module

  Manages ACI Fabric Wide Settings

  Location in GUI:
  `System` » `System Settings` » `Fabric-Wide Settings`

  ## Examples

  ```hcl
  {{ include "./examples/complete/main.tf" }}
  ```

  {{ .Requirements }}

  {{ .Providers }}

  {{ .Inputs }}

  {{ .Outputs }}

  {{ .Resources }}

output:
  file: README.md
  mode: replace

sort:
  enabled: false
