version: '>= 0.14.0'

formatter: markdown table

content: |-
  [![Tests](https://github.com/netascode/terraform-aci-endpoint-security-group/actions/workflows/test.yml/badge.svg)](https://github.com/netascode/terraform-aci-endpoint-security-group/actions/workflows/test.yml)

  # Terraform ACI Endpoint Security Group Module

  Description

  Location in GUI:
  `Tenants` » `XXX` » `Application Profiles` » `XXX` » `Endpoint Security Groups`

  ## Examples

  ```hcl
  {{ include "./examples/complete/main.tf" }}
  ```

  {{ .Requirements }}

  {{ .Providers }}

  {{ .Inputs }}

  {{ .Outputs }}

  {{ .Resources }}

output:
  file: README.md
  mode: replace

sort:
  enabled: false
