version: '>= 0.14.0'

formatter: markdown table

content: |-
  [![Tests](https://github.com/netascode/terraform-aci-fabric-leaf-interface-profile/actions/workflows/test.yml/badge.svg)](https://github.com/netascode/terraform-aci-fabric-leaf-interface-profile/actions/workflows/test.yml)

  # Terraform ACI Fabric Leaf Interface Profile Module

  Manages ACI Fabric Leaf Interface Profile

  Location in GUI:
  `Fabric` » `Fabric Policies` » `Interfaces` » `Leaf Interfaces` » `Profiles`

  ## Examples

  ```hcl
  {{ include "./examples/complete/main.tf" }}
  ```

  {{ .Requirements }}

  {{ .Providers }}

  {{ .Inputs }}

  {{ .Outputs }}

  {{ .Resources }}

output:
  file: README.md
  mode: replace

sort:
  enabled: false
