version: '>= 0.14.0'

formatter: markdown table

content: |-
  # Terraform ACI BFD Switch Policy Module

  Manages ACI BFD Switch Policy

  Location in GUI:
  `Fabric` » `Access Policies` » `Policies` » `Switch` » `BFD`

  ## Examples

  ```hcl
  {{ include "./examples/complete/main.tf" }}
  ```

  {{ .Requirements }}

  {{ .Providers }}

  {{ .Inputs }}

  {{ .Outputs }}

  {{ .Resources }}

output:
  file: README.md
  mode: replace

sort:
  enabled: false
