version: ">= 0.14.0"

formatter: markdown table

content: |-
  # Terraform ACI Track List Module

  Manages ACI Track List

  Location in GUI:
  `Tenants` » `XXX` » `Policies` » `Protocol` » `IP SLA` » `Track Lists`

  ## Examples

  ```hcl
  {{ include "./examples/complete/main.tf" }}
  ```

  {{ .Requirements }}

  {{ .Providers }}

  {{ .Inputs }}

  {{ .Outputs }}

  {{ .Resources }}

output:
  file: README.md
  mode: replace

sort:
  enabled: false
