version: '>= 0.14.0'

formatter: markdown table

content: |-
  [![Tests](https://github.com/netascode/terraform-aci-dhcp-option-policy/actions/workflows/test.yml/badge.svg)](https://github.com/netascode/terraform-aci-dhcp-option-policy/actions/workflows/test.yml)

  # Terraform ACI DHCP Option Policy Module

  Manages ACI DHCP Option Policy

  Location in GUI:
  `Tenants` » `XXX` » `Policies` » `Protocol` » `DHCP` » `Option Policies`

  ## Examples

  ```hcl
  {{ include "./examples/complete/main.tf" }}
  ```

  {{ .Requirements }}

  {{ .Providers }}

  {{ .Inputs }}

  {{ .Outputs }}

  {{ .Resources }}

output:
  file: README.md
  mode: replace

sort:
  enabled: false
