version: '>= 0.14.0'

formatter: markdown table

content: |-
  [![Tests](https://github.com/netascode/terraform-aci-device-selection-policy/actions/workflows/test.yml/badge.svg)](https://github.com/netascode/terraform-aci-device-selection-policy/actions/workflows/test.yml)

  # Terraform ACI Device Selection Policy Module

  Manages ACI Device Selection Policy

  Location in GUI:
  `Tenants` » `XXX` » `Services` » `L4-L7` » `Device Selection Policies`

  ## Examples

  ```hcl
  {{ include "./examples/complete/main.tf" }}
  ```

  {{ .Requirements }}

  {{ .Providers }}

  {{ .Inputs }}

  {{ .Outputs }}

  {{ .Resources }}

output:
  file: README.md
  mode: replace

sort:
  enabled: false
