version: '>= 0.14.0'

formatter: markdown table

content: |-
  # Terraform ACI L3out Interface Profile Module

  Manages ACI L3out Interface Profile

  Location in GUI:
  `Tenants` » `XXX` » `Networking` » `L3outs` » `XXX` » `Logical Node Profiles` » `XXX` » `Logical Interface Profiles`

  ## Examples

  ```hcl
  {{ include "./examples/complete/main.tf" }}
  ```

  {{ .Requirements }}

  {{ .Providers }}

  {{ .Inputs }}

  {{ .Outputs }}

  {{ .Resources }}

output:
  file: README.md
  mode: replace

sort:
  enabled: false
