version: '>= 0.14.0'

formatter: markdown table

content: |-
  [![Tests](https://github.com/netascode/terraform-aci-oob-node-address/actions/workflows/test.yml/badge.svg)](https://github.com/netascode/terraform-aci-oob-node-address/actions/workflows/test.yml)

  # Terraform ACI OOB Node Address Module

  Manages ACI OOB Node Address

  Location in GUI:
  `Tenants` » `mgmt` » `Node Management Addresses` » `Static Node Management Addresses`

  ## Examples

  ```hcl
  {{ include "./examples/complete/main.tf" }}
  ```

  {{ .Requirements }}

  {{ .Providers }}

  {{ .Inputs }}

  {{ .Outputs }}

  {{ .Resources }}

output:
  file: README.md
  mode: replace

sort:
  enabled: false
