version: '>= 0.14.0'

formatter: markdown table

content: |-
  [![Tests](https://github.com/netascode/terraform-aci-ip-aging/actions/workflows/test.yml/badge.svg)](https://github.com/netascode/terraform-aci-ip-aging/actions/workflows/test.yml)

  # Terraform ACI IP Aging Module

  Manages ACI IP Aging

  Location in GUI:
  `System` » `System Settings` » `Endpoint Controls` » `IP Aging`

  ## Examples

  ```hcl
  {{ include "./examples/complete/main.tf" }}
  ```

  {{ .Requirements }}

  {{ .Providers }}

  {{ .Inputs }}

  {{ .Outputs }}

  {{ .Resources }}

output:
  file: README.md
  mode: replace

sort:
  enabled: false
