version: '>= 0.14.0'

formatter: markdown table

content: |-
  # Terraform ACI Error Disabled Recovery Module

  Manages ACI Error Disabled Recovery

  Location in GUI:
  `Fabric` » `Access Policies` » `Policies` » `Global` » `Error Disabled Recovery Policy`

  ## Examples

  ```hcl
  {{ include "./examples/complete/main.tf" }}
  ```

  {{ .Requirements }}

  {{ .Providers }}

  {{ .Inputs }}

  {{ .Outputs }}

  {{ .Resources }}

output:
  file: README.md
  mode: replace

sort:
  enabled: false
