version: '>= 0.14.0'

formatter: markdown table

content: |-
  # Terraform CoPP Interface Policy Module

  Manages CoPP Interface Policy

  Location in GUI:
  `Fabric` » `Access Policies` » `Policies` » `Interface` » `CoPP Interface`

  ## Examples

  ```hcl
  {{ include "./examples/complete/main.tf" }}
  ```

  {{ .Requirements }}

  {{ .Providers }}

  {{ .Inputs }}

  {{ .Outputs }}

  {{ .Resources }}

output:
  file: README.md
  mode: replace

sort:
  enabled: false
