version: '>= 0.14.0'

formatter: markdown table

content: |-
  [![Tests](https://github.com/netascode/terraform-aci-system-global-gipo/actions/workflows/test.yml/badge.svg)](https://github.com/netascode/terraform-aci-system-global-gipo/actions/workflows/test.yml)

  # Terraform ACI System Global GIPO Module

  Manages ACI System Global GIPO

  Location in GUI:
  `System` » `System Settings` » `System Gloval GIPo`

  ## Examples

  ```hcl
  {{ include "./examples/complete/main.tf" }}
  ```

  {{ .Requirements }}

  {{ .Providers }}

  {{ .Inputs }}

  {{ .Outputs }}

  {{ .Resources }}

output:
  file: README.md
  mode: replace

sort:
  enabled: false
