version: '>= 0.14.0'

formatter: markdown table

content: |-
  [![Tests](https://github.com/netascode/terraform-aci-tacacs/actions/workflows/test.yml/badge.svg)](https://github.com/netascode/terraform-aci-tacacs/actions/workflows/test.yml)

  # Terraform ACI TACACS Module

  Manages ACI TACACS

  Location in GUI:
  `Admin` » `AAA` » `Authentication` » `TACACS`

  ## Examples

  ```hcl
  {{ include "./examples/complete/main.tf" }}
  ```

  {{ .Requirements }}

  {{ .Providers }}

  {{ .Inputs }}

  {{ .Outputs }}

  {{ .Resources }}

output:
  file: README.md
  mode: replace

sort:
  enabled: false
