version: '>= 0.14.0'

formatter: markdown table

content: |-
  # Terraform ACI Nutanix VMM Domain Module

  Manages ACI VMware VMM Domain

  Location in GUI:
  `Virtual Networking` » `Nutanix`

  ## Examples

  ```hcl
  {{ include "./examples/complete/main.tf" }}
  ```

  {{ .Requirements }}

  {{ .Providers }}

  {{ .Inputs }}

  {{ .Outputs }}

  {{ .Resources }}

output:
  file: README.md
  mode: replace

sort:
  enabled: false
