version: '>= 0.14.0'

formatter: markdown table

content: |-
  [![Tests](https://github.com/netascode/terraform-aci-mcp/actions/workflows/test.yml/badge.svg)](https://github.com/netascode/terraform-aci-mcp/actions/workflows/test.yml)

  # Terraform ACI MCP Module

  Description

  Location in GUI:
  `Fabric` » `Access Policies` » `Policies` » `Global` » `MCP Instance Policy default`

  ## Examples

  ```hcl
  {{ include "./examples/complete/main.tf" }}
  ```

  {{ .Requirements }}

  {{ .Providers }}

  {{ .Inputs }}

  {{ .Outputs }}

  {{ .Resources }}

output:
  file: README.md
  mode: replace

sort:
  enabled: false
