version: '>= 0.14.0'

formatter: markdown table

content: |-
  [![Tests](https://github.com/netascode/terraform-aci-vspan-session/actions/workflows/test.yml/badge.svg)](https://github.com/netascode/terraform-aci-vspan-session/actions/workflows/test.yml)

  # Terraform ACI VSPAN Session Module

  Manages ACI VSPAN Session

  Location in GUI:
  `Fabric` » `Access Policies` » `Policies` » `Troubleshooting` » `VSPAN` » `VSPAN Sessions`

  ## Examples

  ```hcl
  {{ include "./examples/complete/main.tf" }}
  ```

  {{ .Requirements }}

  {{ .Providers }}

  {{ .Inputs }}

  {{ .Outputs }}

  {{ .Resources }}

output:
  file: README.md
  mode: replace

sort:
  enabled: false
