version: '>= 0.14.0'

formatter: markdown table

content: |-
  # Endpoint IP Tag Module

  Manages Endpoint IP Tags

  Location in GUI:
  `Tenants` » `XXX` » `Policies` » `Endpoint Tags` » `Endpoint MAC`

  ## Examples

  ```hcl
  {{ include "./examples/complete/main.tf" }}
  ```

  {{ .Requirements }}

  {{ .Providers }}

  {{ .Inputs }}

  {{ .Outputs }}

  {{ .Resources }}

output:
  file: README.md
  mode: replace

sort:
  enabled: false
