version: '>= 0.14.0'

formatter: markdown table

content: |-
  [![Tests](https://github.com/netascode/terraform-aci-trust-control-policy/actions/workflows/test.yml/badge.svg)](https://github.com/netascode/terraform-aci-trust-control-policy/actions/workflows/test.yml)

  # Terraform ACI Trust Control Policy Module

  Manages ACI Trust Control Policy

  Location in GUI:
  `Tenants` » `XXX` » `Policies` » `First Hop Security` » `Trust Control Policies`

  ## Examples

  ```hcl
  {{ include "./examples/complete/main.tf" }}
  ```

  {{ .Requirements }}

  {{ .Providers }}

  {{ .Inputs }}

  {{ .Outputs }}

  {{ .Resources }}

output:
  file: README.md
  mode: replace

sort:
  enabled: false
