version: '>= 0.14.0'

formatter: markdown table

content: |-
  # Terraform ACI Netflow Monitor Module

  Manages ACI Netflow Monitors

  Location in GUI:
  `Fabric` » `Access Policies` » `Policies` » `Interface Policies` » `NetFlow` » `Netflow Records`

  ## Examples

  ```hcl
  {{ include "./examples/complete/main.tf" }}
  ```

  {{ .Requirements }}

  {{ .Providers }}

  {{ .Inputs }}

  {{ .Outputs }}

  {{ .Resources }}

output:
  file: README.md
  mode: replace

sort:
  enabled: false
