version: '>= 0.14.0'

formatter: markdown table

content: |-
  # Terraform ACI Managed Node Connectivity Group Module

  Manages ACI Managed Node Connectivity Group

  Location in GUI:
  `Tenant` » `mgmt` » `Managed Node Connectivity Groups`

  ## Examples

  ```hcl
  {{ include "./examples/complete/main.tf" }}
  ```

  {{ .Requirements }}

  {{ .Providers }}

  {{ .Inputs }}

  {{ .Outputs }}

  {{ .Resources }}

output:
  file: README.md
  mode: replace

sort:
  enabled: false
