version: '>= 0.14.0'

formatter: markdown table

content: |-
  # Terraform ACI RADIUS Module

  Manages ACI RADIUS

  Location in GUI:
  `Admin` » `AAA` » `Authentication` » `RADIUS`

  ## Examples

  ```hcl
  {{ include "./examples/complete/main.tf" }}
  ```

  {{ .Requirements }}

  {{ .Providers }}

  {{ .Inputs }}

  {{ .Outputs }}

  {{ .Resources }}

output:
  file: README.md
  mode: replace

sort:
  enabled: false
