version: '>= 0.14.0'

formatter: markdown table

content: |-
  # Terraform ACI Atomic Counter Module

  Manages Atomic Counter

  Location in GUI:
  `Operations` » `Visualization` » `Atomic Counter`

  ## Examples

  ```hcl
  {{ include "./examples/complete/main.tf" }}
  ```

  {{ .Requirements }}

  {{ .Providers }}

  {{ .Inputs }}

  {{ .Outputs }}

  {{ .Resources }}

output:
  file: README.md
  mode: replace

sort:
  enabled: false
