version: '>= 0.14.0'

formatter: markdown table

content: |-
  # Terraform ACI MACsec Keychain Policies Module

  Manages ACI MACsec Keychain Policy

  Location in GUI:
  `Fabric` » `Access Policies` » `Policies` » `Interface` » `MACsec` » `MACsec KeyChain Policies`

  ## Examples

  ```hcl
  {{ include "./examples/complete/main.tf" }}
  ```

  {{ .Requirements }}

  {{ .Providers }}

  {{ .Inputs }}

  {{ .Outputs }}

  {{ .Resources }}

output:
  file: README.md
  mode: replace

sort:
  enabled: false
