version: '>= 0.14.0'

formatter: markdown table

content: |-
  # Example

  ```hcl
  {{ include "main.tf" }}
  ```

  {{ .Requirements }}

  {{ .Providers }}

  {{ .Modules }}

output:
  file: README.md
  mode: replace

sort:
  enabled: false
