version: '>= 0.14.0'

formatter: markdown table

content: |-
  [![Tests](https://github.com/netascode/terraform-aci-vmware-vmm-domain/actions/workflows/test.yml/badge.svg)](https://github.com/netascode/terraform-aci-vmware-vmm-domain/actions/workflows/test.yml)

  # Terraform ACI VMware VMM Domain Module

  Manages ACI VMware VMM Domain

  Location in GUI:
  `Virtual Networking` » `VMware`

  ## Examples

  ```hcl
  {{ include "./examples/complete/main.tf" }}
  ```

  {{ .Requirements }}

  {{ .Providers }}

  {{ .Inputs }}

  {{ .Outputs }}

  {{ .Resources }}

output:
  file: README.md
  mode: replace

sort:
  enabled: false
