version: '>= 0.14.0'

formatter: markdown table

content: |-
  # Terraform ACI Proxy Policy Module

  Manages ACI HTTP/HTTPS Proxy Policy

  Location in GUI:
  `System` » `System Settings` » `Proxy Policy`

  ## Examples

  ```hcl
  {{ include "./examples/complete/main.tf" }}
  ```

  {{ .Requirements }}

  {{ .Providers }}

  {{ .Inputs }}

  {{ .Outputs }}

  {{ .Resources }}

output:
  file: README.md
  mode: replace

sort:
  enabled: false
