version: '>= 0.14.0'

formatter: markdown table

content: |-
  [![Tests](https://github.com/netascode/terraform-aci-qos/actions/workflows/test.yml/badge.svg)](https://github.com/netascode/terraform-aci-qos/actions/workflows/test.yml)

  # Terraform ACI QoS Module

  Manages ACI QoS

  Location in GUI:
  `Fabric` » `Access Policies` » `Policies` » `Global` » `QOS Class`

  ## Examples

  ```hcl
  {{ include "./examples/complete/main.tf" }}
  ```

  {{ .Requirements }}

  {{ .Providers }}

  {{ .Inputs }}

  {{ .Outputs }}

  {{ .Resources }}

output:
  file: README.md
  mode: replace

sort:
  enabled: false
