version: '>= 0.14.0'

formatter: markdown table

content: |-
  # Terraform ACI MPLS Custom QoS Policy

  MPLS Custom QoS Policy

  Location in GUI:
  `Tenants` » `infra` » `Policies` » `Protocol` » `MPLS Custom QoS Policy`

  ## Examples

  ```hcl
  {{ include "./examples/complete/main.tf" }}
  ```

  {{ .Requirements }}

  {{ .Providers }}

  {{ .Inputs }}

  {{ .Outputs }}

  {{ .Resources }}

output:
  file: README.md
  mode: replace

sort:
  enabled: false
